### ISSUE TITLE
Copy and paste on macos

### ISSUE THREAD

**Issue by HenryQuan** [dawnGlare/padsim#5]
Thank you for the great website and it has been really useful for my project. There is one issue with the little input box on macos. As you know, macos uses Command + C instead of Ctrl + C for copy (same for cut and paste) and I cannot copy paste from the input box. I think by changing [this line](https://github.com/dawnGlare/padsim/blob/14361e9fc0d3511db2fcde68fd220dc12e76a2ca/pad.js#L1076), the problem can be resolved. I think the key name for command is `metaKey` which is the windows key on windows.

**Comment by dawnGlare** [comment]
I have changed the relevant lines to include the metaKey command, although I cannot confirm that it works as intended on a mac based system.

**Comment by HenryQuan** [comment]
No problem, I will try it on my machine later and see if it works.

**Comment by HenryQuan** [comment]
I have tried it on my machine and it does work as expected. Thank you!
